version: "3"
services:
  nginx: 
    image: nginx:latest
    container_name: http_rev_proxy
    volumes:
      # - /opt/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      # - /opt/www:/opt/www
    ports:
      - 80:80
      # - 443:443