version: "3"
services:
  web:
    image: nginx:stable
    volumes:
      - ./opt/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./opt/nginx/conf.d:/etc/nginx/conf.d
      # - ./opt/www:/opt/www
    ports:
      - "80:80"
      # - "443:443"
    networks:
      - proxy_webnet
networks:
   proxy_webnet: