version: "3"
services:
  nginx:
    container_name: cyberskill_nginx
    image: nginx:stable
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/webroot:/usr/share/nginx/html
      - ./logs/nginx:/var/log/nginx
    ports:
      - "80:80"
      # - "443:443"
    networks:
      - proxy_webnet
networks:
   proxy_webnet: